### ISSUE TITLE
Create a list of all twitter users

### ISSUE THREAD

**Issue by erikvanegmond** [erikvanegmond/25-lima#4]

**Comment by joswezenberg** [comment]
Ik kan m'n data nog niet zo krijgen zoals ik ze wil maar in pseudo code wil ik dit maken:
from fixedTweets load files
from files remove all but relevant features
go through lines
    if user in line is not in [userlist] then append #unieke users listen
    (misschien een kolom aan het einde toevoegen met occurance)
    else in last column or row 'user' increment occurance by 1

van het resultaat wil ik een nieuwe file maken die we kunnen inzien en mee kunnen werken.

Maar ik kom er ook niet zo goed uit hoe ik de data goed weergegeven krijg, zodat ik ook goed kan achterhalen wat ik precies waar vandaan moet lezen. Maar volgens mij, als ik de data schoon kan maken hoef ik niet elke feature in dictionary style uit te lezen maar kan ik de hele regel gewoon meenemen.

**Comment by joswezenberg** [comment]
gevonden issue: in de discription van users worden ',' gebruikt die json verkeerd classificeerd als seperator.
waarde van discription stond als groen geclassificeerd, maar is denk ik niet cruciaal voor nu.

**Comment by erikvanegmond** [comment]
Ah, mooi dat je het hebt opgelost! Wat ook nog een optie is is het in een dict op te slaan. Dan kan je elke gebruiker toevoegen met als key de username. En als value weer een dict met de features van de User. Dan hoef je niet te controleren of iemand er al in staat. Als een key niet bestaat word hij aangemaakt. En als de key al wel bestaat word de vorige value overschreven. Maar omdat de values het zelfde zijn geeft dat niet. Afhankelijk van je oorspronkelijke implementatie kan deze iets langzamer zijn met het laden. Maar een dict is optimaal in her opzoeken van de key. Dan kunnen we dus razendsnel alle useful features van een user ophalen. Maar daar kunnen we anders morgen nog wel naar kijken

**Comment by ghost** [comment]
morgen hier over hebben! het strippen werkt zo slecht dat nieuwe dict maken misschien veel betere optie is - zo ook voor tweets - ookal echt niet zuinigst qua resources en complexity

**Comment by ghost** [comment]
future work
